### ISSUE TITLE
quadratic O(n^2) processing time in AnyModel.joined /output on eagerLoad of many-to-many tables.

### ISSUE THREAD

**Issue by astrotuna201** [vapor/fluent-kit#163] opened 2020-02-18 13:18 UTC
## Background

After solving a Sibling related problem [https://github.com/vapor/fluent-kit/issues/155] the eagerLoad injection (processing part) seemed to be slow. Here, two tables "Expeditions" and "Persons" are related via three many-to-many relations, where each "Expedition" can have three many-to-many relationships to Persons. The actual production app where this was noticed has 306 items in Expeditions, and 570 in Persons, related through three pivot tables.

### Prerequisites

Vapor 4 (4.0.0-beta.3.21) /Fluent-Kit (1.0.0-beta.4), Swift 5.2 toolchain, Postgresql 12. Tested on macOS 10.14.6, Xcode 11.3.1 w. 5.2 toolchain 2020-02-16

### Installing
A sample repository is available here: https://github.com/astrotuna201/vaporTest.git
It requires a Postgresql table "vaporTestStore", db owner "vaporTestOwner" and appropriate password. The postgresql port on the remote test machine was on 15432. Tests were run in both, release and debug mode via importing the Package.swift file in Xcode. The project contains the usual persons, expeditions index routes, as well as expeditionsEagerTimed and personsEagerTimed routes that output the total time taken from initial request to final output (triggered by an external GET request on, e.g., "http://127.0.0.1:8080/expeditionsEagerTimed"). Tests were run with and without indices on the postgresql table without noticeable difference. The project includes Seed Migrations to populate the database.
Example run line on macOS:
```
DATABASE_HOST=127.0.0.1 DATABASE_PASSWORD="XXXXXX" /Library/Developer/Toolchains/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-02-16-a.xctoolchain/usr/bin/swift run -c release Run migrate

DATABASE_HOST=127.0.0.1 DATABASE_PASSWORD="XXXXXX" /Library/Developer/Toolchains/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-02-16-a.xctoolchain/usr/bin/swift run -c release Run serve --port 8082 --log trace
```

then trigger timing by GET request on 
```
http://127.0.0.1:8082/expeditionsEagerTimed
```

## Initial findings:
While there is some small overhead on the actual postgresql DB access, most of the run-time of the Vapor project is spent in processing the results. There seems to be a quadratic relationship O(n^2) between items in the Model that has the Siblings eagerLoaded queried via
```
Expedition.query(on: req.db)
    .with(\.$coChiefs) //the relations are of type `Person`
    .with(\.$loggingStaffScientists)
    .with(\.$staffScientists)
    .all()
```

### "Instruments" trace:
The instruments trace (release mode) indicates that most of the processing time is spent in the Fluent-Kit.Model. functions "AnyModel.joined"  mostly ... followed by AnyModel.output(from:).
Details and Vapor Trace can be inspected at [https://github.com/vapor/fluent-kit/issues/155].

The runtime table is
| #Persons | #Expeditions | Release (s) | Debug (s) |
|----------|--------------|-------------|-----------|
| 100      | 100          | 1.4         | 5.2       |
| 100      | 200          | 5.7         | 19.4      |
| 100      | 300          | 11.5        | 44.0      |
| 100      | 400          | 20.3        | 86.8      |
| 100      | 600          | 47.2        | 175.6     |

**Comment by 0xTim** [comment] 2020-02-18 13:24
It would be great to add something like this to performance tests in the test suite to catch future regressions and measure improvements

**Comment by tanner0101** [comment] 2020-02-18 16:48
Instruments pointing to `AnyModel.joined` seems like a fluke since that method doesn't really do anything, but maybe not. My initial guess is that filtering the related result set for each model is where we're getting O(n^m) where n is the main query result count and m is the eager loaded result count. Each model in the main query must search the entire eager loaded result set to find matching models. This could be fixed by generating a lookup cache first. I will take a look to see if this assumption is correct or if there's something else going on. Thanks for the detailed report @astrotuna201 !

**Comment by tanner0101** [comment] 2020-02-18 16:53
@0xTim I agree 100%. I'm just not really sure how to implement something like that. Apple has their own servers they can test on which allow them to get reliable performance numbers for things like SwiftNIO and Swift itself. Testing on CI can sometimes yield inconsistent results. It's better than nothing, though. Maybe GitHub actions can help us here. 

Ideally we would spin up a cheap, bare metal server that could do performance testing for us. With a simple Vapor API or something to report numbers back via a bot to GH.

**Comment by 0xTim** [comment] 2020-02-18 17:03
Looking around there are lots of things doing/for performance testing on GH actions so it might be stable enough. I guess ideally we'd have a sweet of performance tests, run them in parallel on 3+ machines and take a median etc. 

Another option is a custom GH action that does something like spin up an EC2 instance, run tests, post the data back and tear it down. I think for the first iteration using GH actions would be good enough and then we could investigate other options if it becomes a hindrance

**Comment by tanner0101** [comment] 2020-02-18 17:35
Yeah I agree. Maybe GH actions will be more stable than Circle. Doing parallel jobs is also a good idea if we need to average out inconsistencies.

**Closed** 2020-02-18 18:18 UTC
Labels: bug

**Comment by tanner0101** [comment] 2020-02-18 18:19
https://github.com/vapor/fluent-kit/releases/tag/1.0.0-beta.4.4 should greatly improve performance. There's definitely still room for other performance improvements here (and elsewhere in FluentKit for that matter), but I'm marking this as closed since siblings eager loading runtime is no longer quadratic.

**Comment by astrotuna201** [comment] 2020-02-18 20:20
Many thanks, that fixed it. And what an amazing turn-around time!
