### ISSUE TITLE
Enum Array type doesn't work.

### ISSUE THREAD

**Issue by mlight3** [vapor/fluent-kit#449] opened 2021-08-13 16:21 UTC
I am trying to migrate the existing server to a new swift server with vapor.  So I am making models with existing tables, but Enum array type doesn't work. (/w postresSQL 13.2)

Here is my tables and models.
```sql
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    uid character varying(100) NOT NULL UNIQUE,
    firstname character varying(20),
    lastname character varying(20),
    nickname character varying(30),
    profile_url character varying(500),
    email character varying(100) NOT NULL UNIQUE,
    user_status user_status,
    birthday date,
    timezone character varying(30),
    roles role[],
    about_me character varying(255),
    last_login timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE "role" AS ENUM (
  'admin',
  'developer',
  'qa'
)
```

```swift
final class Users: Model {
    static let schema = "users"
    
    @ID(custom: "id", generatedBy: .database)
    var id: Int?
    
    @OptionalField(key: "roles")
    var roles: [Role]?
    
    init() { }
}

enum Role: String, Codable {
    case admin
    case developer
    case qa
}
```

When I try to execute a query on users, I got this error message.
```
failure(invalid field: roles type: Optional<Array<Role>> error: Unexpected data type: UNKNOWN 16387. Expected array.)
```

Is there any way to register a new type?
I also tried to use `PostgresDataConvertible`, and I couldn't make it.

**Comment by bdrelling** [comment] 2022-07-23 23:13
I believe this is a duplicate of #374.

**Comment by 0xTim** [comment] 2022-07-24 09:04
Yes let's gather everything together in a central place

**Closed by 0xTim** 2022-07-24 09:04 UTC
Labels: bug
